#!/bin/bash
# usage: call-abnfgen START SYNTAX [COUNT]

TESTFILE=`mktemp` || exit 1
TMPDIR=`mktemp -d` || exit 1
# generate test files
abnfgen -d $TMPDIR -s $1 -n ${3:-50} $2
# combine test-cases into one file, separated by '\0'
for i in `ls $TMPDIR`;
do
  if [ -s $TESTFILE ]; then
    # file is not empty, add delimiter
    echo -ne '\00' >> $TESTFILE
  fi
  cat $TMPDIR/$i >> $TESTFILE
done    
# remove the test files
rm -rf $TMPDIR

# execute the parser
../bnfcheck -e 0 $1 :../share/conf/abnf.conf $2 < $TESTFILE

RETCODE=$?
if [ $RETCODE != 0 ]; then
  # we got an error, do NOT remove the test file
  echo "$0: error occured, see $TESTFILE"
  exit 1
fi

# all tests passed, remove the test file
rm -f $TESTFILE

# end of file
