#!/bin/bash
# usage: call-abnfgen GRAMMAR START [COUNT]

TESTFILE=`mktemp` || exit 1
TMPDIR=`mktemp -d` || exit 1
# generate test files
abnfgen -d $TMPDIR -n ${3:-50} $1
# combine test-cases into one file, separated by '\0'
for i in `ls $TMPDIR`;
do
  cat $TMPDIR/$i >> $TESTFILE
  echo -ne '\00' >> $TESTFILE
done    
# remove the test files
rm -rf $TMPDIR

# execute the parser
../bnfcheck $1 ../share/conf/abnf.conf $2 < $TESTFILE

RETCODE=$?
if [ $RETCODE != 0 ]; then
  # we got an error, do NOT remove the test file
  echo "$1: error occured, see $TESTFILE"
  exit 1
fi

# all tests passed, remove the test file
rm -f $TESTFILE

# end of file
